# CMake generated Testfile for 
# Source directory: /home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api
# Build directory: /home/shreyas/G/shr-fuj/oneDNN_open_source/build_il/tests/gtests/graph/api
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_graph_c_api_add_op "test_graph_c_api_add_op")
set_tests_properties(test_graph_c_api_add_op PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_c_api_constant_cache "test_graph_c_api_constant_cache")
set_tests_properties(test_graph_c_api_constant_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_c_api_filter "test_graph_c_api_filter")
set_tests_properties(test_graph_c_api_filter PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_c_api_graph "test_graph_c_api_graph")
set_tests_properties(test_graph_c_api_graph PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_c_api_logical_tensor "test_graph_c_api_logical_tensor")
set_tests_properties(test_graph_c_api_logical_tensor PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_c_api_op "test_graph_c_api_op")
set_tests_properties(test_graph_c_api_op PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_cpp_api_constant_cache "test_graph_cpp_api_constant_cache")
set_tests_properties(test_graph_cpp_api_constant_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_cpp_api_engine "test_graph_cpp_api_engine")
set_tests_properties(test_graph_cpp_api_engine PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_cpp_api_graph "test_graph_cpp_api_graph")
set_tests_properties(test_graph_cpp_api_graph PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_cpp_api_logical_tensor "test_graph_cpp_api_logical_tensor")
set_tests_properties(test_graph_cpp_api_logical_tensor PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_cpp_api_op "test_graph_cpp_api_op")
set_tests_properties(test_graph_cpp_api_op PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_cpp_api_tensor "test_graph_cpp_api_tensor")
set_tests_properties(test_graph_cpp_api_tensor PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;31;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;76;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_c_api_compile_usm_cpu "test_graph_c_api_compile" "--engine=cpu")
set_tests_properties(test_graph_c_api_compile_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;26;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;88;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_c_api_compile_parametrized_usm_cpu "test_graph_c_api_compile_parametrized" "--engine=cpu")
set_tests_properties(test_graph_c_api_compile_parametrized_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;26;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;88;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_cpp_api_compile_usm_cpu "test_graph_cpp_api_compile" "--engine=cpu")
set_tests_properties(test_graph_cpp_api_compile_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;26;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;88;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
add_test(test_graph_cpp_api_partition_usm_cpu "test_graph_cpp_api_partition" "--engine=cpu")
set_tests_properties(test_graph_cpp_api_partition_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;26;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;88;register_graph_api_test_suite;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/api/CMakeLists.txt;0;")
