var hierarchy =
[
    [ "dnnl::deconvolution_backward_data::desc", "structdnnl_1_1deconvolution__backward__data_1_1desc.html", null ],
    [ "dnnl::resampling_backward::desc", "structdnnl_1_1resampling__backward_1_1desc.html", null ],
    [ "dnnl::logsoftmax_backward::desc", "structdnnl_1_1logsoftmax__backward_1_1desc.html", null ],
    [ "dnnl::pooling_v2_forward::desc", "structdnnl_1_1pooling__v2__forward_1_1desc.html", null ],
    [ "dnnl::pooling_v2_backward::desc", "structdnnl_1_1pooling__v2__backward_1_1desc.html", null ],
    [ "dnnl::batch_normalization_forward::desc", "structdnnl_1_1batch__normalization__forward_1_1desc.html", null ],
    [ "dnnl::prelu_forward::desc", "structdnnl_1_1prelu__forward_1_1desc.html", null ],
    [ "dnnl::deconvolution_backward_weights::desc", "structdnnl_1_1deconvolution__backward__weights_1_1desc.html", null ],
    [ "dnnl::prelu_backward::desc", "structdnnl_1_1prelu__backward_1_1desc.html", null ],
    [ "dnnl::batch_normalization_backward::desc", "structdnnl_1_1batch__normalization__backward_1_1desc.html", null ],
    [ "dnnl::layer_normalization_forward::desc", "structdnnl_1_1layer__normalization__forward_1_1desc.html", null ],
    [ "dnnl::reduction::desc", "structdnnl_1_1reduction_1_1desc.html", null ],
    [ "dnnl::lrn_forward::desc", "structdnnl_1_1lrn__forward_1_1desc.html", null ],
    [ "dnnl::layer_normalization_backward::desc", "structdnnl_1_1layer__normalization__backward_1_1desc.html", null ],
    [ "dnnl::inner_product_forward::desc", "structdnnl_1_1inner__product__forward_1_1desc.html", null ],
    [ "dnnl::inner_product_backward_data::desc", "structdnnl_1_1inner__product__backward__data_1_1desc.html", null ],
    [ "dnnl::lrn_backward::desc", "structdnnl_1_1lrn__backward_1_1desc.html", null ],
    [ "dnnl::inner_product_backward_weights::desc", "structdnnl_1_1inner__product__backward__weights_1_1desc.html", null ],
    [ "dnnl::convolution_forward::desc", "structdnnl_1_1convolution__forward_1_1desc.html", null ],
    [ "dnnl::pooling_forward::desc", "structdnnl_1_1pooling__forward_1_1desc.html", null ],
    [ "dnnl::vanilla_rnn_forward::desc", "structdnnl_1_1vanilla__rnn__forward_1_1desc.html", null ],
    [ "dnnl::convolution_backward_data::desc", "structdnnl_1_1convolution__backward__data_1_1desc.html", null ],
    [ "dnnl::vanilla_rnn_backward::desc", "structdnnl_1_1vanilla__rnn__backward_1_1desc.html", null ],
    [ "dnnl::pooling_backward::desc", "structdnnl_1_1pooling__backward_1_1desc.html", null ],
    [ "dnnl::memory::desc", "structdnnl_1_1memory_1_1desc.html", null ],
    [ "dnnl::eltwise_forward::desc", "structdnnl_1_1eltwise__forward_1_1desc.html", null ],
    [ "dnnl::lstm_forward::desc", "structdnnl_1_1lstm__forward_1_1desc.html", null ],
    [ "dnnl::lstm_backward::desc", "structdnnl_1_1lstm__backward_1_1desc.html", null ],
    [ "dnnl::gru_forward::desc", "structdnnl_1_1gru__forward_1_1desc.html", null ],
    [ "dnnl::convolution_backward_weights::desc", "structdnnl_1_1convolution__backward__weights_1_1desc.html", null ],
    [ "dnnl::eltwise_backward::desc", "structdnnl_1_1eltwise__backward_1_1desc.html", null ],
    [ "dnnl::gru_backward::desc", "structdnnl_1_1gru__backward_1_1desc.html", null ],
    [ "dnnl::lbr_gru_forward::desc", "structdnnl_1_1lbr__gru__forward_1_1desc.html", null ],
    [ "dnnl::lbr_gru_backward::desc", "structdnnl_1_1lbr__gru__backward_1_1desc.html", null ],
    [ "dnnl::softmax_forward::desc", "structdnnl_1_1softmax__forward_1_1desc.html", null ],
    [ "dnnl::shuffle_forward::desc", "structdnnl_1_1shuffle__forward_1_1desc.html", null ],
    [ "dnnl::deconvolution_forward::desc", "structdnnl_1_1deconvolution__forward_1_1desc.html", null ],
    [ "dnnl::shuffle_backward::desc", "structdnnl_1_1shuffle__backward_1_1desc.html", null ],
    [ "dnnl::softmax_backward::desc", "structdnnl_1_1softmax__backward_1_1desc.html", null ],
    [ "dnnl::binary::desc", "structdnnl_1_1binary_1_1desc.html", null ],
    [ "dnnl::matmul::desc", "structdnnl_1_1matmul_1_1desc.html", null ],
    [ "dnnl::logsoftmax_forward::desc", "structdnnl_1_1logsoftmax__forward_1_1desc.html", null ],
    [ "dnnl::resampling_forward::desc", "structdnnl_1_1resampling__forward_1_1desc.html", null ],
    [ "dnnl_batch_normalization_desc_t", "structdnnl__batch__normalization__desc__t.html", null ],
    [ "dnnl_binary_desc_t", "structdnnl__binary__desc__t.html", null ],
    [ "dnnl_blocking_desc_t", "structdnnl__blocking__desc__t.html", null ],
    [ "dnnl_convolution_desc_t", "structdnnl__convolution__desc__t.html", null ],
    [ "dnnl_eltwise_desc_t", "structdnnl__eltwise__desc__t.html", null ],
    [ "dnnl_engine", "structdnnl__engine.html", null ],
    [ "dnnl_exec_arg_t", "structdnnl__exec__arg__t.html", null ],
    [ "dnnl_inner_product_desc_t", "structdnnl__inner__product__desc__t.html", null ],
    [ "dnnl_layer_normalization_desc_t", "structdnnl__layer__normalization__desc__t.html", null ],
    [ "dnnl_lrn_desc_t", "structdnnl__lrn__desc__t.html", null ],
    [ "dnnl_matmul_desc_t", "structdnnl__matmul__desc__t.html", null ],
    [ "dnnl_memory", "structdnnl__memory.html", null ],
    [ "dnnl_memory_desc_t", "structdnnl__memory__desc__t.html", null ],
    [ "dnnl_memory_extra_desc_t", "structdnnl__memory__extra__desc__t.html", null ],
    [ "dnnl_pooling_desc_t", "structdnnl__pooling__desc__t.html", null ],
    [ "dnnl_pooling_v2_desc_t", "structdnnl__pooling__v2__desc__t.html", null ],
    [ "dnnl_post_ops", "structdnnl__post__ops.html", null ],
    [ "dnnl_primitive", "structdnnl__primitive.html", null ],
    [ "dnnl_primitive_attr", "structdnnl__primitive__attr.html", null ],
    [ "dnnl_primitive_desc", "structdnnl__primitive__desc.html", null ],
    [ "dnnl_primitive_desc_iterator", "structdnnl__primitive__desc__iterator.html", null ],
    [ "dnnl_reduction_desc_t", "structdnnl__reduction__desc__t.html", null ],
    [ "dnnl_resampling_desc_t", "structdnnl__resampling__desc__t.html", null ],
    [ "dnnl_rnn_desc_t", "structdnnl__rnn__desc__t.html", null ],
    [ "dnnl_rnn_packed_desc_t", "structdnnl__rnn__packed__desc__t.html", null ],
    [ "dnnl_shuffle_desc_t", "structdnnl__shuffle__desc__t.html", null ],
    [ "dnnl_softmax_desc_t", "structdnnl__softmax__desc__t.html", null ],
    [ "dnnl_stream", "structdnnl__stream.html", null ],
    [ "dnnl_version_t", "structdnnl__version__t.html", null ],
    [ "dnnl_wino_desc_t", "structdnnl__wino__desc__t.html", null ],
    [ "dnnl::error", "structdnnl_1_1error.html", null ],
    [ "dnnl::handle< T, traits >", "structdnnl_1_1handle.html", null ],
    [ "dnnl::handle< dnnl_engine_t >", "structdnnl_1_1handle.html", [
      [ "dnnl::engine", "structdnnl_1_1engine.html", null ]
    ] ],
    [ "dnnl::handle< dnnl_memory_t >", "structdnnl_1_1handle.html", [
      [ "dnnl::memory", "structdnnl_1_1memory.html", null ]
    ] ],
    [ "dnnl::handle< dnnl_post_ops_t >", "structdnnl_1_1handle.html", [
      [ "dnnl::post_ops", "structdnnl_1_1post__ops.html", null ]
    ] ],
    [ "dnnl::handle< dnnl_primitive_attr_t >", "structdnnl_1_1handle.html", [
      [ "dnnl::primitive_attr", "structdnnl_1_1primitive__attr.html", null ]
    ] ],
    [ "dnnl::handle< dnnl_primitive_desc_iterator >", "structdnnl_1_1handle.html", null ],
    [ "dnnl::handle< dnnl_primitive_desc_t >", "structdnnl_1_1handle.html", [
      [ "dnnl::primitive_desc_base", "structdnnl_1_1primitive__desc__base.html", [
        [ "dnnl::concat::primitive_desc", "structdnnl_1_1concat_1_1primitive__desc.html", null ],
        [ "dnnl::primitive_desc", "structdnnl_1_1primitive__desc.html", [
          [ "dnnl::batch_normalization_backward::primitive_desc", "structdnnl_1_1batch__normalization__backward_1_1primitive__desc.html", null ],
          [ "dnnl::batch_normalization_forward::primitive_desc", "structdnnl_1_1batch__normalization__forward_1_1primitive__desc.html", null ],
          [ "dnnl::binary::primitive_desc", "structdnnl_1_1binary_1_1primitive__desc.html", null ],
          [ "dnnl::convolution_backward_data::primitive_desc", "structdnnl_1_1convolution__backward__data_1_1primitive__desc.html", null ],
          [ "dnnl::convolution_backward_weights::primitive_desc", "structdnnl_1_1convolution__backward__weights_1_1primitive__desc.html", null ],
          [ "dnnl::convolution_forward::primitive_desc", "structdnnl_1_1convolution__forward_1_1primitive__desc.html", null ],
          [ "dnnl::deconvolution_backward_data::primitive_desc", "structdnnl_1_1deconvolution__backward__data_1_1primitive__desc.html", null ],
          [ "dnnl::deconvolution_backward_weights::primitive_desc", "structdnnl_1_1deconvolution__backward__weights_1_1primitive__desc.html", null ],
          [ "dnnl::deconvolution_forward::primitive_desc", "structdnnl_1_1deconvolution__forward_1_1primitive__desc.html", null ],
          [ "dnnl::eltwise_backward::primitive_desc", "structdnnl_1_1eltwise__backward_1_1primitive__desc.html", null ],
          [ "dnnl::eltwise_forward::primitive_desc", "structdnnl_1_1eltwise__forward_1_1primitive__desc.html", null ],
          [ "dnnl::inner_product_backward_data::primitive_desc", "structdnnl_1_1inner__product__backward__data_1_1primitive__desc.html", null ],
          [ "dnnl::inner_product_backward_weights::primitive_desc", "structdnnl_1_1inner__product__backward__weights_1_1primitive__desc.html", null ],
          [ "dnnl::inner_product_forward::primitive_desc", "structdnnl_1_1inner__product__forward_1_1primitive__desc.html", null ],
          [ "dnnl::layer_normalization_backward::primitive_desc", "structdnnl_1_1layer__normalization__backward_1_1primitive__desc.html", null ],
          [ "dnnl::layer_normalization_forward::primitive_desc", "structdnnl_1_1layer__normalization__forward_1_1primitive__desc.html", null ],
          [ "dnnl::logsoftmax_backward::primitive_desc", "structdnnl_1_1logsoftmax__backward_1_1primitive__desc.html", null ],
          [ "dnnl::logsoftmax_forward::primitive_desc", "structdnnl_1_1logsoftmax__forward_1_1primitive__desc.html", null ],
          [ "dnnl::lrn_backward::primitive_desc", "structdnnl_1_1lrn__backward_1_1primitive__desc.html", null ],
          [ "dnnl::lrn_forward::primitive_desc", "structdnnl_1_1lrn__forward_1_1primitive__desc.html", null ],
          [ "dnnl::matmul::primitive_desc", "structdnnl_1_1matmul_1_1primitive__desc.html", null ],
          [ "dnnl::pooling_backward::primitive_desc", "structdnnl_1_1pooling__backward_1_1primitive__desc.html", null ],
          [ "dnnl::pooling_forward::primitive_desc", "structdnnl_1_1pooling__forward_1_1primitive__desc.html", null ],
          [ "dnnl::pooling_v2_backward::primitive_desc", "structdnnl_1_1pooling__v2__backward_1_1primitive__desc.html", null ],
          [ "dnnl::pooling_v2_forward::primitive_desc", "structdnnl_1_1pooling__v2__forward_1_1primitive__desc.html", null ],
          [ "dnnl::prelu_backward::primitive_desc", "structdnnl_1_1prelu__backward_1_1primitive__desc.html", null ],
          [ "dnnl::prelu_forward::primitive_desc", "structdnnl_1_1prelu__forward_1_1primitive__desc.html", null ],
          [ "dnnl::reduction::primitive_desc", "structdnnl_1_1reduction_1_1primitive__desc.html", null ],
          [ "dnnl::resampling_backward::primitive_desc", "structdnnl_1_1resampling__backward_1_1primitive__desc.html", null ],
          [ "dnnl::resampling_forward::primitive_desc", "structdnnl_1_1resampling__forward_1_1primitive__desc.html", null ],
          [ "dnnl::rnn_primitive_desc_base", "structdnnl_1_1rnn__primitive__desc__base.html", [
            [ "dnnl::gru_backward::primitive_desc", "structdnnl_1_1gru__backward_1_1primitive__desc.html", null ],
            [ "dnnl::gru_forward::primitive_desc", "structdnnl_1_1gru__forward_1_1primitive__desc.html", null ],
            [ "dnnl::lbr_gru_backward::primitive_desc", "structdnnl_1_1lbr__gru__backward_1_1primitive__desc.html", null ],
            [ "dnnl::lbr_gru_forward::primitive_desc", "structdnnl_1_1lbr__gru__forward_1_1primitive__desc.html", null ],
            [ "dnnl::lstm_backward::primitive_desc", "structdnnl_1_1lstm__backward_1_1primitive__desc.html", null ],
            [ "dnnl::lstm_forward::primitive_desc", "structdnnl_1_1lstm__forward_1_1primitive__desc.html", null ],
            [ "dnnl::vanilla_rnn_backward::primitive_desc", "structdnnl_1_1vanilla__rnn__backward_1_1primitive__desc.html", null ],
            [ "dnnl::vanilla_rnn_forward::primitive_desc", "structdnnl_1_1vanilla__rnn__forward_1_1primitive__desc.html", null ]
          ] ],
          [ "dnnl::shuffle_backward::primitive_desc", "structdnnl_1_1shuffle__backward_1_1primitive__desc.html", null ],
          [ "dnnl::shuffle_forward::primitive_desc", "structdnnl_1_1shuffle__forward_1_1primitive__desc.html", null ],
          [ "dnnl::softmax_backward::primitive_desc", "structdnnl_1_1softmax__backward_1_1primitive__desc.html", null ],
          [ "dnnl::softmax_forward::primitive_desc", "structdnnl_1_1softmax__forward_1_1primitive__desc.html", null ]
        ] ],
        [ "dnnl::reorder::primitive_desc", "structdnnl_1_1reorder_1_1primitive__desc.html", null ],
        [ "dnnl::sum::primitive_desc", "structdnnl_1_1sum_1_1primitive__desc.html", null ]
      ] ]
    ] ],
    [ "dnnl::handle< dnnl_primitive_t >", "structdnnl_1_1handle.html", [
      [ "dnnl::primitive", "structdnnl_1_1primitive.html", [
        [ "dnnl::batch_normalization_backward", "structdnnl_1_1batch__normalization__backward.html", null ],
        [ "dnnl::batch_normalization_forward", "structdnnl_1_1batch__normalization__forward.html", null ],
        [ "dnnl::binary", "structdnnl_1_1binary.html", null ],
        [ "dnnl::concat", "structdnnl_1_1concat.html", null ],
        [ "dnnl::convolution_backward_data", "structdnnl_1_1convolution__backward__data.html", null ],
        [ "dnnl::convolution_backward_weights", "structdnnl_1_1convolution__backward__weights.html", null ],
        [ "dnnl::convolution_forward", "structdnnl_1_1convolution__forward.html", null ],
        [ "dnnl::deconvolution_backward_data", "structdnnl_1_1deconvolution__backward__data.html", null ],
        [ "dnnl::deconvolution_backward_weights", "structdnnl_1_1deconvolution__backward__weights.html", null ],
        [ "dnnl::deconvolution_forward", "structdnnl_1_1deconvolution__forward.html", null ],
        [ "dnnl::eltwise_backward", "structdnnl_1_1eltwise__backward.html", null ],
        [ "dnnl::eltwise_forward", "structdnnl_1_1eltwise__forward.html", null ],
        [ "dnnl::gru_backward", "structdnnl_1_1gru__backward.html", null ],
        [ "dnnl::gru_forward", "structdnnl_1_1gru__forward.html", null ],
        [ "dnnl::inner_product_backward_data", "structdnnl_1_1inner__product__backward__data.html", null ],
        [ "dnnl::inner_product_backward_weights", "structdnnl_1_1inner__product__backward__weights.html", null ],
        [ "dnnl::inner_product_forward", "structdnnl_1_1inner__product__forward.html", null ],
        [ "dnnl::layer_normalization_backward", "structdnnl_1_1layer__normalization__backward.html", null ],
        [ "dnnl::layer_normalization_forward", "structdnnl_1_1layer__normalization__forward.html", null ],
        [ "dnnl::lbr_gru_backward", "structdnnl_1_1lbr__gru__backward.html", null ],
        [ "dnnl::lbr_gru_forward", "structdnnl_1_1lbr__gru__forward.html", null ],
        [ "dnnl::logsoftmax_backward", "structdnnl_1_1logsoftmax__backward.html", null ],
        [ "dnnl::logsoftmax_forward", "structdnnl_1_1logsoftmax__forward.html", null ],
        [ "dnnl::lrn_backward", "structdnnl_1_1lrn__backward.html", null ],
        [ "dnnl::lrn_forward", "structdnnl_1_1lrn__forward.html", null ],
        [ "dnnl::lstm_backward", "structdnnl_1_1lstm__backward.html", null ],
        [ "dnnl::lstm_forward", "structdnnl_1_1lstm__forward.html", null ],
        [ "dnnl::matmul", "structdnnl_1_1matmul.html", null ],
        [ "dnnl::pooling_backward", "structdnnl_1_1pooling__backward.html", null ],
        [ "dnnl::pooling_forward", "structdnnl_1_1pooling__forward.html", null ],
        [ "dnnl::pooling_v2_backward", "structdnnl_1_1pooling__v2__backward.html", null ],
        [ "dnnl::pooling_v2_forward", "structdnnl_1_1pooling__v2__forward.html", null ],
        [ "dnnl::prelu_backward", "structdnnl_1_1prelu__backward.html", null ],
        [ "dnnl::prelu_forward", "structdnnl_1_1prelu__forward.html", null ],
        [ "dnnl::reduction", "structdnnl_1_1reduction.html", null ],
        [ "dnnl::reorder", "structdnnl_1_1reorder.html", null ],
        [ "dnnl::resampling_backward", "structdnnl_1_1resampling__backward.html", null ],
        [ "dnnl::resampling_forward", "structdnnl_1_1resampling__forward.html", null ],
        [ "dnnl::shuffle_backward", "structdnnl_1_1shuffle__backward.html", null ],
        [ "dnnl::shuffle_forward", "structdnnl_1_1shuffle__forward.html", null ],
        [ "dnnl::softmax_backward", "structdnnl_1_1softmax__backward.html", null ],
        [ "dnnl::softmax_forward", "structdnnl_1_1softmax__forward.html", null ],
        [ "dnnl::sum", "structdnnl_1_1sum.html", null ],
        [ "dnnl::vanilla_rnn_backward", "structdnnl_1_1vanilla__rnn__backward.html", null ],
        [ "dnnl::vanilla_rnn_forward", "structdnnl_1_1vanilla__rnn__forward.html", null ]
      ] ]
    ] ],
    [ "dnnl::handle< dnnl_stream_t >", "structdnnl_1_1handle.html", [
      [ "dnnl::stream", "structdnnl_1_1stream.html", null ]
    ] ],
    [ "dnnl::handle_traits< T >", "structdnnl_1_1handle__traits.html", null ],
    [ "dnnl::threadpool_interop::threadpool_iface", "structdnnl_1_1threadpool__interop_1_1threadpool__iface.html", null ]
];