# CMake generated Testfile for 
# Source directory: /home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit
# Build directory: /home/shreyas/G/shr-fuj/oneDNN_open_source/build_il/tests/gtests/graph/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_graph_unit_interface "test_graph_unit" "--gtest_filter=test_interface_*")
set_tests_properties(test_graph_unit_interface PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_fake "test_graph_unit" "--gtest_filter=test_fake_*")
set_tests_properties(test_graph_unit_fake PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_common "test_graph_unit" "--gtest_filter=test_common_*")
set_tests_properties(test_graph_unit_dnnl_common PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_constant_cache "test_graph_unit" "--gtest_filter=test_constant_cache_*")
set_tests_properties(test_graph_unit_dnnl_constant_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_dnnl_infer_shape "test_graph_unit" "--gtest_filter=test_dnnl_infer_shape_*")
set_tests_properties(test_graph_unit_dnnl_dnnl_infer_shape PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_dnnl_partition_impl "test_graph_unit" "--gtest_filter=test_dnnl_partition_impl_*")
set_tests_properties(test_graph_unit_dnnl_dnnl_partition_impl PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_fusion_info "test_graph_unit" "--gtest_filter=test_fusion_info_*")
set_tests_properties(test_graph_unit_dnnl_fusion_info PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_graph "test_graph_unit" "--gtest_filter=test_graph_*")
set_tests_properties(test_graph_unit_dnnl_graph PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_insert_ops "test_graph_unit" "--gtest_filter=test_insert_ops_*")
set_tests_properties(test_graph_unit_dnnl_insert_ops PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_internal_attrs "test_graph_unit" "--gtest_filter=test_internal_attrs_*")
set_tests_properties(test_graph_unit_dnnl_internal_attrs PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_layout_id "test_graph_unit" "--gtest_filter=test_layout_id_*")
set_tests_properties(test_graph_unit_dnnl_layout_id PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_layout_propagator "test_graph_unit" "--gtest_filter=test_layout_propagator_*")
set_tests_properties(test_graph_unit_dnnl_layout_propagator PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_logical_tensor "test_graph_unit" "--gtest_filter=test_logical_tensor_*")
set_tests_properties(test_graph_unit_dnnl_logical_tensor PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_memory_planning "test_graph_unit" "--gtest_filter=test_memory_planning_*")
set_tests_properties(test_graph_unit_dnnl_memory_planning PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_op_executable "test_graph_unit" "--gtest_filter=test_op_executable_*")
set_tests_properties(test_graph_unit_dnnl_op_executable PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_op_schema "test_graph_unit" "--gtest_filter=test_op_schema_*")
set_tests_properties(test_graph_unit_dnnl_op_schema PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_partition "test_graph_unit" "--gtest_filter=test_partition_*")
set_tests_properties(test_graph_unit_dnnl_partition PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_pass "test_graph_unit" "--gtest_filter=test_pass_*")
set_tests_properties(test_graph_unit_dnnl_pass PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_scratchpad "test_graph_unit" "--gtest_filter=test_scratchpad_*")
set_tests_properties(test_graph_unit_dnnl_scratchpad PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_select "test_graph_unit" "--gtest_filter=test_select_*")
set_tests_properties(test_graph_unit_dnnl_select PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_subgraph_pass "test_graph_unit" "--gtest_filter=test_subgraph_pass_*")
set_tests_properties(test_graph_unit_dnnl_subgraph_pass PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_thread_local_cache "test_graph_unit" "--gtest_filter=test_thread_local_cache_*")
set_tests_properties(test_graph_unit_dnnl_thread_local_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_batch_norm_usm_cpu "test_graph_unit" "--gtest_filter=test_batch_norm_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_batch_norm_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_binary_op_usm_cpu "test_graph_unit" "--gtest_filter=test_binary_op_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_binary_op_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_bmm_usm_cpu "test_graph_unit" "--gtest_filter=test_bmm_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_bmm_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_compiled_partition_usm_cpu "test_graph_unit" "--gtest_filter=test_compiled_partition_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_compiled_partition_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_concat_usm_cpu "test_graph_unit" "--gtest_filter=test_concat_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_concat_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_conv_usm_cpu "test_graph_unit" "--gtest_filter=test_conv_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_conv_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_convtranspose_usm_cpu "test_graph_unit" "--gtest_filter=test_convtranspose_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_convtranspose_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_dequantize_usm_cpu "test_graph_unit" "--gtest_filter=test_dequantize_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_dequantize_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_eltwise_usm_cpu "test_graph_unit" "--gtest_filter=test_eltwise_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_eltwise_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_interpolate_usm_cpu "test_graph_unit" "--gtest_filter=test_interpolate_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_interpolate_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_large_partition_usm_cpu "test_graph_unit" "--gtest_filter=test_large_partition_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_large_partition_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_layer_norm_usm_cpu "test_graph_unit" "--gtest_filter=test_layer_norm_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_layer_norm_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_matmul_usm_cpu "test_graph_unit" "--gtest_filter=test_matmul_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_matmul_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_pool_usm_cpu "test_graph_unit" "--gtest_filter=test_pool_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_pool_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_prelu_usm_cpu "test_graph_unit" "--gtest_filter=test_prelu_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_prelu_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_quantize_usm_cpu "test_graph_unit" "--gtest_filter=test_quantize_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_quantize_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_reduce_usm_cpu "test_graph_unit" "--gtest_filter=test_reduce_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_reduce_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_reorder_usm_cpu "test_graph_unit" "--gtest_filter=test_reorder_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_reorder_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_sdp_decomp_usm_cpu "test_graph_unit" "--gtest_filter=test_sdp_decomp_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_sdp_decomp_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_softmax_usm_cpu "test_graph_unit" "--gtest_filter=test_softmax_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_softmax_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_dnnl_typecast_usm_cpu "test_graph_unit" "--gtest_filter=test_typecast_*" "--engine=cpu")
set_tests_properties(test_graph_unit_dnnl_typecast_usm_cpu PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;86;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
add_test(test_graph_unit_utils "test_graph_unit" "--gtest_filter=test_utils_*")
set_tests_properties(test_graph_unit_utils PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;91;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/tests/gtests/graph/unit/CMakeLists.txt;0;")
subdirs("interface")
subdirs("backend")
subdirs("utils")
