var annotated_dup =
[
    [ "dnnl", "namespacednnl.html", "namespacednnl" ],
    [ "dnnl_batch_normalization_desc_t", "structdnnl__batch__normalization__desc__t.html", "structdnnl__batch__normalization__desc__t" ],
    [ "dnnl_binary_desc_t", "structdnnl__binary__desc__t.html", "structdnnl__binary__desc__t" ],
    [ "dnnl_blocking_desc_t", "structdnnl__blocking__desc__t.html", "structdnnl__blocking__desc__t" ],
    [ "dnnl_convolution_desc_t", "structdnnl__convolution__desc__t.html", "structdnnl__convolution__desc__t" ],
    [ "dnnl_eltwise_desc_t", "structdnnl__eltwise__desc__t.html", "structdnnl__eltwise__desc__t" ],
    [ "dnnl_engine", "structdnnl__engine.html", null ],
    [ "dnnl_exec_arg_t", "structdnnl__exec__arg__t.html", "structdnnl__exec__arg__t" ],
    [ "dnnl_inner_product_desc_t", "structdnnl__inner__product__desc__t.html", "structdnnl__inner__product__desc__t" ],
    [ "dnnl_layer_normalization_desc_t", "structdnnl__layer__normalization__desc__t.html", "structdnnl__layer__normalization__desc__t" ],
    [ "dnnl_lrn_desc_t", "structdnnl__lrn__desc__t.html", "structdnnl__lrn__desc__t" ],
    [ "dnnl_matmul_desc_t", "structdnnl__matmul__desc__t.html", "structdnnl__matmul__desc__t" ],
    [ "dnnl_memory", "structdnnl__memory.html", null ],
    [ "dnnl_memory_desc_t", "structdnnl__memory__desc__t.html", "structdnnl__memory__desc__t" ],
    [ "dnnl_memory_extra_desc_t", "structdnnl__memory__extra__desc__t.html", "structdnnl__memory__extra__desc__t" ],
    [ "dnnl_pooling_desc_t", "structdnnl__pooling__desc__t.html", "structdnnl__pooling__desc__t" ],
    [ "dnnl_post_ops", "structdnnl__post__ops.html", null ],
    [ "dnnl_primitive", "structdnnl__primitive.html", null ],
    [ "dnnl_primitive_attr", "structdnnl__primitive__attr.html", null ],
    [ "dnnl_primitive_desc", "structdnnl__primitive__desc.html", null ],
    [ "dnnl_primitive_desc_iterator", "structdnnl__primitive__desc__iterator.html", null ],
    [ "dnnl_resampling_desc_t", "structdnnl__resampling__desc__t.html", "structdnnl__resampling__desc__t" ],
    [ "dnnl_rnn_desc_t", "structdnnl__rnn__desc__t.html", "structdnnl__rnn__desc__t" ],
    [ "dnnl_rnn_packed_desc_t", "structdnnl__rnn__packed__desc__t.html", null ],
    [ "dnnl_shuffle_desc_t", "structdnnl__shuffle__desc__t.html", "structdnnl__shuffle__desc__t" ],
    [ "dnnl_softmax_desc_t", "structdnnl__softmax__desc__t.html", "structdnnl__softmax__desc__t" ],
    [ "dnnl_stream", "structdnnl__stream.html", null ],
    [ "dnnl_version_t", "structdnnl__version__t.html", "structdnnl__version__t" ],
    [ "dnnl_wino_desc_t", "structdnnl__wino__desc__t.html", null ]
];