# CMake generated Testfile for 
# Source directory: /home/shreyas/G/shr-fuj/oneDNN_open_source/examples
# Build directory: /home/shreyas/G/shr-fuj/oneDNN_open_source/build_il/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(cpu-bnorm-u8-via-binary-postops-cpp "bnorm-u8-via-binary-postops-cpp" "cpu")
set_tests_properties(cpu-bnorm-u8-via-binary-postops-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-cnn-inference-f32-c "cnn-inference-f32-c" "cpu")
set_tests_properties(cpu-cnn-inference-f32-c PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-cnn-inference-f32-cpp "cnn-inference-f32-cpp" "cpu")
set_tests_properties(cpu-cnn-inference-f32-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-cnn-inference-int8-cpp "cnn-inference-int8-cpp" "cpu")
set_tests_properties(cpu-cnn-inference-int8-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-cnn-training-bf16-cpp "cnn-training-bf16-cpp" "cpu")
set_tests_properties(cpu-cnn-training-bf16-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-cnn-training-f32-cpp "cnn-training-f32-cpp" "cpu")
set_tests_properties(cpu-cnn-training-f32-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-cnn-training-f32-c "cpu-cnn-training-f32-c")
set_tests_properties(cpu-cnn-training-f32-c PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;52;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;140;register_exe;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-rnn-inference-f32-cpp "cpu-rnn-inference-f32-cpp")
set_tests_properties(cpu-rnn-inference-f32-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;52;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;140;register_exe;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-rnn-inference-int8-cpp "cpu-rnn-inference-int8-cpp")
set_tests_properties(cpu-rnn-inference-int8-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;52;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;140;register_exe;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-getting-started-cpp "getting-started-cpp" "cpu")
set_tests_properties(cpu-getting-started-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-graph-getting-started-cpp "cpu-graph-getting-started-cpp")
set_tests_properties(cpu-graph-getting-started-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;52;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;140;register_exe;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-graph-inference-int8-cpp "cpu-graph-inference-int8-cpp")
set_tests_properties(cpu-graph-inference-int8-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;52;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;140;register_exe;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-graph-single-op-partition-cpp "cpu-graph-single-op-partition-cpp")
set_tests_properties(cpu-graph-single-op-partition-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;52;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;140;register_exe;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-matmul-perf-cpp "matmul-perf-cpp" "cpu")
set_tests_properties(cpu-matmul-perf-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-memory-format-propagation-cpp "memory-format-propagation-cpp" "cpu")
set_tests_properties(cpu-memory-format-propagation-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-performance-profiling-cpp "performance-profiling-cpp" "cpu")
set_tests_properties(cpu-performance-profiling-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-augru-cpp "primitives-augru-cpp" "cpu")
set_tests_properties(cpu-primitives-augru-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-batch-normalization-cpp "primitives-batch-normalization-cpp" "cpu")
set_tests_properties(cpu-primitives-batch-normalization-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-binary-cpp "primitives-binary-cpp" "cpu")
set_tests_properties(cpu-primitives-binary-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-concat-cpp "primitives-concat-cpp" "cpu")
set_tests_properties(cpu-primitives-concat-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-convolution-cpp "primitives-convolution-cpp" "cpu")
set_tests_properties(cpu-primitives-convolution-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-eltwise-cpp "primitives-eltwise-cpp" "cpu")
set_tests_properties(cpu-primitives-eltwise-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-group-normalization-cpp "primitives-group-normalization-cpp" "cpu")
set_tests_properties(cpu-primitives-group-normalization-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-inner-product-cpp "primitives-inner-product-cpp" "cpu")
set_tests_properties(cpu-primitives-inner-product-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-layer-normalization-cpp "primitives-layer-normalization-cpp" "cpu")
set_tests_properties(cpu-primitives-layer-normalization-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-lrn-cpp "primitives-lrn-cpp" "cpu")
set_tests_properties(cpu-primitives-lrn-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-lstm-cpp "primitives-lstm-cpp" "cpu")
set_tests_properties(cpu-primitives-lstm-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-matmul-cpp "primitives-matmul-cpp" "cpu")
set_tests_properties(cpu-primitives-matmul-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-pooling-cpp "primitives-pooling-cpp" "cpu")
set_tests_properties(cpu-primitives-pooling-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-prelu-cpp "primitives-prelu-cpp" "cpu")
set_tests_properties(cpu-primitives-prelu-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-reduction-cpp "primitives-reduction-cpp" "cpu")
set_tests_properties(cpu-primitives-reduction-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-reorder-cpp "primitives-reorder-cpp" "cpu")
set_tests_properties(cpu-primitives-reorder-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-resampling-cpp "primitives-resampling-cpp" "cpu")
set_tests_properties(cpu-primitives-resampling-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-shuffle-cpp "primitives-shuffle-cpp" "cpu")
set_tests_properties(cpu-primitives-shuffle-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-softmax-cpp "primitives-softmax-cpp" "cpu")
set_tests_properties(cpu-primitives-softmax-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-primitives-sum-cpp "primitives-sum-cpp" "cpu")
set_tests_properties(cpu-primitives-sum-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-rnn-training-f32-cpp "rnn-training-f32-cpp" "cpu")
set_tests_properties(cpu-rnn-training-f32-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-tutorials-matmul-matmul-quantization-cpp "cpu-tutorials-matmul-matmul-quantization-cpp")
set_tests_properties(cpu-tutorials-matmul-matmul-quantization-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;52;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;140;register_exe;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-tutorials-matmul-sgemm-and-matmul-cpp "cpu-tutorials-matmul-sgemm-and-matmul-cpp")
set_tests_properties(cpu-tutorials-matmul-sgemm-and-matmul-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;52;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;140;register_exe;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-tutorials-matmul-inference-int8-matmul-cpp "tutorials-matmul-inference-int8-matmul-cpp" "cpu")
set_tests_properties(cpu-tutorials-matmul-inference-int8-matmul-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
add_test(cpu-tutorials-matmul-weights-decompression-matmul-cpp "tutorials-matmul-weights-decompression-matmul-cpp" "cpu")
set_tests_properties(cpu-tutorials-matmul-weights-decompression-matmul-cpp PROPERTIES  _BACKTRACE_TRIPLES "/home/shreyas/G/shr-fuj/oneDNN_open_source/cmake/utils.cmake;40;add_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;152;add_dnnl_test;/home/shreyas/G/shr-fuj/oneDNN_open_source/examples/CMakeLists.txt;0;")
